name: My Custom Branch Workflow

on:
  push:
    branches:
      stam

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a script
        run: echo "Hello from my-feature-branch!"
